define(function() {
    var needLogin = true;
    var menu = [
        // level 1 menu
        {
            hash:'#test',
            path:'adm/test',
            level:'1',
            requireLogin:false,
            checkSIMStatus:false
        } ,
        {
            hash:'#login',
            path:'login',
            level:'1',
            requireLogin:false,
            checkSIMStatus:false
        } ,
        {
            hash:'#index_status',
            path:'index_status',
            level:'1',
            requireLogin:false,
            checkSIMStatus:false
        } ,
        {
            hash:'#iran_login',
            path:'iran_login',
            level:'1',
            requireLogin:false,
            checkSIMStatus:false
        } ,
        {
            hash:'#change_user_password',
            path:'change_user_password',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        } ,
        {
            hash:'#info',
            path:'info',
            level:'1',
            requireLogin:false,
            checkSIMStatus:false
        } ,
        {
            hash:'#home',
            path:'home',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        } ,
        {
            hash:'#status',
            path:'status/device_info',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#sms',
            path:'sms/smslist',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#phonebook',
            path:'phonebook/phonebook',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#setting',
            path:'adm/quick_setting',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:true
        }

        // level 2 menu
        ,
        {
            hash:'#quick_setting',
            path:'adm/quick_setting',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#system_settings',
            path:'system/system_settings',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#device_settings',
            path:'system/device_settings',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#modify_password',
            path:'system/modify_password',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#modify_username',
            path:'system/modify_username',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#restore_factory_setting',
            path:'system/restore_factory_setting',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#automatic_dialing',
            path:'system/automatic_dialing',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#time_setting',
            path:'system/time_setting',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#system_service',
            path:'system/system_service',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#usb',
            path:'system/usb',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#frequency',
            path:'system/frequency',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#mcc_mnc_locking',
            path:'system/mcc_mnc_locking',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#net_lockpci',
            path:'network/net_lockpci',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#export_load_configuration',
            path:'system/export_load_configuration',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#system_security',
            path:'system/system_security',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#postroute',
            path:'system/postroute',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#ddos',
            path:'system/ddos',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#wifi_calibration',
            path:'system/wifi_calibration',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#lan_limits_speed_info',
            path:'system/lan_limits_speed_info',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#ping',
            path:'system/ping',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#send_at',
            path:'system/send_at',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#trace',
            path:'system/trace',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#tcpdump',
            path:'system/tcpdump',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#logs',
            path:'system/logs',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#system_check',
            path:'system/system_check',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#reset_protection_password',
            path:'system/reset_protection_password',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#system_log',
            path:'system/system_log',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#system_upgrade',
            path:'system/system_upgrade',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#modem_upgrade',
            path:'system/modem_upgrade',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#config_upgrade',
            path:'system/config_upgrade',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#network_tools',
            path:'system/network_tools',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#modem_log_catching',
            path:'system/modem_log_catching',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#help',
            path:'system/help',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#reboot',
            path:'system/reboot',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#unlock',
            path:'system/unlock',
            level:'2',
            parent:'#home',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#net_setting',
            path:'network/dial_setting_cpe',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#wifi',
            path:'wifi/wifi_basic',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#device_setting',
            path:'adm/password',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#firewall',
            path:'firewall/firewall',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#router_setting',
            path:'adm/lan',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#dhcp1_settings',
            path:'adm/dhcp1_settings',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#dhcp2_settings',
            path:'adm/dhcp2_settings',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#static_ip',
            path:'adm/staticIp',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#route_settings',
            path:'system/route_settings',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#access_control',
            path:'system/access_control',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#backup_data',
            path:'adm/backup_data',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#sipServer',
            path:'adm/sipServer',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#volte',
            path:'adm/volte',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#voice_call_type',
            path:'adm/voice_call_type',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#hotline',
            path:'adm/hotline',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#digitmap',
            path:'adm/digitmap',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#pptp',
            path:'adm/pptp',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#wb_mode',
            path:'adm/wb_mode',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#uri_type',
            path:'adm/uri_type',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#remoteLogin',
            path:'adm/remoteLogin',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#httpsPort',
            path:'adm/httpsPort',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#setssid',
            path:'adm/setssid',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#setssid_2',
            path:'adm/setssid_2',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#setssid_3',
            path:'adm/setssid_3',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
		{
            hash:'#ussd',
            path:'ussd/ussd',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#mymascomdiy',
            path:'adm/mymascomdiy',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#mascom',
            path:'adm/mascom',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#monitor',
            path:'adm/monitor',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#group_all',
            path:'phonebook/phonebook',
            level:'2',
            parent:'#phonebook',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#group_common',
            path:'phonebook/phonebook',
            level:'2',
            parent:'#phonebook',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#group_family',
            path:'phonebook/phonebook',
            level:'2',
            parent:'#phonebook',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#group_friend',
            path:'phonebook/phonebook',
            level:'2',
            parent:'#phonebook',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#group_colleague',
            path:'phonebook/phonebook',
            level:'2',
            parent:'#phonebook',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#traffic_alert',
            path:'status/traffic_alert',
            level:'2',
            parent:'#status',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#smslist',
            path:'sms/smslist',
            level:'2',
            parent:'#sms',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#sim_messages',
            path:'sms/sim_messages',
            level:'2',
            parent:'#sms',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#sms_setting',
            path:'sms/sms_setting',
            level:'2',
            parent:'#sms',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#ap_station',
            path:'wifi/ap_station',
            level:'2',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        }
        // level 3 menu
        ,
        {
            hash:'#dial_setting',
            path:'network/dial_setting',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#net_select',
            path:'network/net_select',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#mobile_connection',
            path:'network/mobile_connection',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#apn_setting',
            path:'network/apn_setting',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#volte_apn',
            path:'network/volte_apn',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#l2tp',
            path:'network/l2tp',
            level:'2',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
         {
            hash:'#polarity_reversal',
            path:'network/polarity_reversal',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#setapn_1',
            path:'network/settings_apn1',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#setapn_2',
            path:'network/settings_apn2',
            level:'3',
            parent:'#net_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#wifi_main',
            path:'wifi/wifi_main',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#wifiSwitch',
            path:'wifi/wifiSwitch',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#wifi_guest',
            path:'wifi/wifi_guest',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#station_info',
            path:'wifi/station_info',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
	{
            hash:'#wifi_advance',
            path:'wifi/wifi_advance',
            level:'3',
            parent:'#wifi',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#wps',
            path:'wifi/wps',
            level:'3',
            parent:'#wifi',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
		{
            hash:'#mac_filter',
            path:'wifi/mac_filter',
            level:'3',
            parent:'#wifi',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
            hash:'#hotsporServer',
            path:'wifi/hotsporServer',
            level:'3',
            parent:'#wifi',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#w13Setting',
            path:'wifi/w13Setting',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#password_management',
            path:'adm/password',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#pin_management',
            path:'adm/pin',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:true
        },
        {
            hash:'#sleep_mode',
            path:'wifi/sleep_mode',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
         hash:'#import_export',
         path:'firewall/import_export',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
         },
		{
			hash: '#tr069config',
			path: 'adm/tr069config',
			level: '3',
			parent: '#device_setting',
			requireLogin:needLogin
		},
         {
            hash: '#snmp',
            path: 'adm/snmp',
            level: '3',
            parent: '#device_setting',
            requireLogin:needLogin
        },
        {
            hash:'#port_filter',
            path:'firewall/port_filter',
            level:'3',
            parent:'#firewall',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#firewall_switch',
            path:'firewall/firewall_switch',
            level:'3',
            parent:'#setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
         {
         hash:'#port_forward',
         path:'firewall/port_forward',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
         },
        {
            hash:'#port_map',
            path:'firewall/port_map',
            level:'3',
            parent:'#firewall',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#upnp',
            path:'firewall/upnp_setting',
            level:'3',
            parent:'#firewall',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#nat',
            path:'firewall/nat',
            level:'3',
            parent:'#firewall',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#dmz',
            path:'firewall/dmz_setting',
            level:'3',
            parent:'#firewall',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
		{
		 hash:'#main_url_filter',
		 path:'firewall/main_url_filter',
		 level:'3',
		 parent:'#firewall',
		 requireLogin:needLogin
		},
        {
         hash:'#url_filter_1',
         path:'firewall/url_filter_1',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
        },
        {
         hash:'#url_filter_2',
         path:'firewall/url_filter_2',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
        },
        {
         hash:'#rate_limit',
         path:'firewall/rate_limit',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
         },
         {
         hash:'#flow_setting',
         path:'firewall/flow_setting',
         level:'3',
         parent:'#firewall',
         requireLogin:needLogin
         },
        {
            hash:'#others',
            path:'adm/others',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#usb',
            path:'usb/usb',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin
        },
        {
            hash:'#ota_update',
            path:'update/ota_update',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#ddns',
            path:'ddns/ddns',
            level:'3',
            parent:'#device_setting',
            requireLogin:needLogin,
            checkSIMStatus:false
        },
        {
            hash:'#parental_control',
            path:'firewall/parental_control',
            level:'1',
            requireLogin:needLogin,
            checkSIMStatus:false
        }

    ];

    return menu;
});
